/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_sim_free: (a: number, b: number) => void;
export const arrowhead_matrix_gi: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const arrowhead_modes: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const arrowhead_modes_gi: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const cavity_field: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const cavity_layers: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const cavity_power_spectrum: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number];
export const cavity_power_spectrum_gi: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number];
export const coupling_sweep: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const coupling_sweep_gi: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number];
export const htc_franck_condon: (a: number, b: number, c: number, d: number) => [number, number];
export const htc_matrix_view: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const htc_spectrum: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const htc_spectrum_multi: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => [number, number];
export const sim_advance: (a: number, b: number, c: number, d: number) => void;
export const sim_cavity_rho_abs: (a: number) => [number, number];
export const sim_emitter_bloch: (a: number) => [number, number];
export const sim_excited_pop: (a: number) => number;
export const sim_husimi: (a: number, b: number, c: number, d: number) => [number, number];
export const sim_min_eigenvalue: (a: number) => number;
export const sim_new: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => number;
export const sim_photon_number: (a: number) => number;
export const sim_purity: (a: number) => number;
export const sim_reset: (a: number) => void;
export const sim_rho_abs: (a: number) => [number, number];
export const sim_rho_imag: (a: number) => [number, number];
export const sim_rho_real: (a: number) => [number, number];
export const sim_time: (a: number) => number;
export const sim_trace: (a: number) => number;
export const sim_von_neumann_entropy: (a: number) => number;
export const sim_wigner: (a: number, b: number, c: number, d: number) => [number, number];
export const sim_wigner_rgba: (a: number, b: number, c: number, d: number, e: number) => [number, number];
export const spectrum: (a: number, b: number, c: number, d: number, e: number, f: number) => [number, number];
export const wigner_of_rho: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number) => [number, number];
export const wigner_rgba_of_rho: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number) => [number, number];
export const cavity_reflectance: (a: number, b: number, c: number, d: number, e: number, f: number, g: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
